language: go
go:
  - 1.5
  - 1.6
  - 1.7
  - tip

sudo: false

notifications:
  email:
    recipients:
      - binet@cern.ch
    on_success: change
    on_failure: always

script:
 - go get -d -t -v ./...
 - go install -v ./...
 - go test -v ./...

