language: go
go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - master

matrix:
 fast_finish: true
 allow_failures:
   - go: master


#sudo: false

notifications:
  email:
    recipients:
      - binet@cern.ch
    on_success: change
    on_failure: always

before_install:
    - git clone git://github.com/jedisct1/libsodium.git
    - ( cd libsodium && ./autogen.sh && ./configure && make && sudo make install && sudo ldconfig )
    - git clone git://github.com/zeromq/libzmq.git
    - ( cd libzmq && ./autogen.sh && ./configure && make && sudo make install && sudo ldconfig )

script:
 - go get -d -t -v ./...
 - go install -v ./...
 - go test -v ./...

