language: go
go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - master
os:
  - linux
matrix:
 fast_finish: true
 allow_failures:
   - go: master

env:
 - TAGS=""

sudo: false

notifications:
  email:
    recipients:
      - binet@cern.ch
    on_success: change
    on_failure: always

script:
 - go get -d -t -v ./...
 - go install -v $TAGS ./...
 - go test $TAGS ./...
 - go test $TAGS -race ./...
